REMOVE="
/system/app/AppLounge
/system/app/eCalendar
/system/app/eDrive
/system/app/eSpeak
/system/app/Mail
/system/app/Maps
/system/app/Message
/system/app/Notes
/system/app/PdfViewer
/system/app/PwaPlayer
/system/app/Tasks
/system/product/app/Browser
/system/product/app/Glimpse
/system/product/app/ExactCalculator
/system/product/app/DeskClock
/system/product/app/Twelve
/system/product/priv-app/Dialer
/system/product/priv-app/Contacts
/system/system_ext/app/FindMyDevice
/system/system_ext/priv-app/BlissWeather
"